import Navigation from "@/components/Navigation";
import Providers from "@/components/Providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navigation />
          <body>{children}</body>
        </Providers>
      </body>
    </html>
  );
}
